Removed obsolete file and clean up directory Support parsing QMI output from qlsort2

diff --git a/qlsort2 b/qlsort2
--- a/qlsort2
+++ b/qlsort2
@@ -1,3 +1,38 @@
+#!/bin/bash
+#
+# Copyright (C) <2012>  Crs Chin<crs.chin@gmail.com>
+# 
+# This program is free software; you can redistribute it and/or modify
+# it under the terms of the GNU General Public License as published by
+# the Free Software Foundation; either version 2 of the License, or
+# (at your option) any later version.
+# 
+# This program is distributed in the hope that it will be useful,
+# but WITHOUT ANY WARRANTY; without even the implied warranty of
+# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+# GNU General Public License for more details.
+# 
+# You should have received a copy of the GNU General Public License
+# along with this program; if not, write to the Free Software
+# Foundation, Inc., 59 Temple Place - Suite 330,
+# Boston, MA 02111-1307, USA.
+#
+
+QCAT_BIN=$(type -p QCAT);
+QCAT_MODULE_PATH="/Applications/QCAT/QCAT/Script";
+
+if [ -n "$QCAT_BIN" ]; then
+    QCAT_MODULE_PATH=$(realpath $(dirname $QCAT_BIN)/../Script/)
+fi
+
+if ! type -p perl > /dev/null;then
+    echo "perl required for this program, abort!";
+    exit -1;
+fi
+
+perl -I "$QCAT_MODULE_PATH" -x $0 "$@"
+exit $?
+
 #!/usr/bin/perl
 #
 # Copyright (C) <2018>  Crs Chin<crs.chin@gmail.com>
